Repository polarismesh/polaris, pull requests merged in 2021-12, with the labels that each got.

#176 [ISSUE #123] fix dirty data bug in standalone mode use boltdb
  store/boltdb/business.go
  store/boltdb/circuitbreaker.go
  store/boltdb/circuitbreaker_test.go
  store/boltdb/handler.go
  store/boltdb/handler_test.go
  store/boltdb/instance.go
  store/boltdb/instance_test.go
  store/boltdb/namespace_test.go
  store/boltdb/platform.go
  store/boltdb/ratelimit.go
  store/boltdb/ratelimit_test.go
  store/boltdb/routing.go
  store/boltdb/routing_test.go
  store/boltdb/service.go
  store/boltdb/service_test.go
  store/boltdb/transaction.go
Labels: bug, store

#151 [ISSUE #119] feat: multi-file log
  bootstrap/server.go
  common/log/config.go
  common/log/default.go
  common/log/options.go
  common/log/scope.go
  common/log/type.go
  config/config.go
  deploy/standalone/k8s/01-polaris-server-config.yaml
  naming/test/main_test.go
  naming/testauthplugin/main_test.go
  polaris-server.yaml
Labels: enhancement

#189 perf:use sync.RWMutex replace sync.Mutex in counter
  common/connlimit/listener.go
Labels: enhancement, apisever

#182 [ISSUE #147] feat: support instance change event
  .gitignore
  bootstrap/server.go
  common/model/naming.go
  common/model/plugin_config_model.go
  healthcheck/cache.go
  healthcheck/check.go
  healthcheck/dispatch.go
  healthcheck/report.go
  healthcheck/server.go
  naming/cache/instance.go
  naming/instance.go
  naming/server.go
  plugin.go
  plugin/discoverevent.go
  plugin/discoverevent/local/event_local.go
  plugin/discoverevent/local/eventbuffer_test.go
  plugin/discoverevent/local/logger.go
  plugin/plugin.go
  polaris-server.yaml
Labels: enhancement, plugin

#196 feat:make Time2String as common function
  common/model/instance.go
  common/model/naming.go
  common/redispool/redis_pool.go
  common/time/time.go
  go.mod
  go.sum
  healthcheck/server.go
  naming/circuitbreaker_config.go
  naming/namespace.go
  naming/platform.go
  naming/ratelimit_config.go
  naming/routing_config.go
  naming/server.go
  naming/service.go
  naming/service_alias.go
  naming/test/main_test.go
  plugin/auth/platform/platform.go
  plugin/discoverstat/discoverlocal/discovercall.go
  plugin/history/logger/history_logger.go
  plugin/statis/local/apicall.go
  store/boltdb/instance.go
  store/boltdb/instance_test.go
  store/sqldb/circuitbreaker_config.go
  store/sqldb/default.go
  store/sqldb/instance.go
  store/sqldb/ratelimit_config.go
  store/sqldb/routing_config.go
  store/sqldb/service.go
Labels: code quality

#209 feat:Unified use utils.NewUUID()
  common/utils/funcs.go
  naming/circuitbreaker_config.go
  naming/instance.go
  naming/namespace.go
  naming/platform.go
  naming/ratelimit_config.go
  naming/routing_config.go
  naming/server.go
  naming/service.go
  naming/service_alias.go
  test/grpc/discover.go
  test/grpc/heartbeat.go
  test/grpc/register.go
  test/grpc/report_client.go
Labels: code quality

#211 [ISSUE #187] Hot fix cannt return namespace
  store/boltdb/namespace.go
  store/boltdb/namespace_test.go
Labels: bug
