Repository polarismesh/polaris, pull requests merged in 2021-11, with the labels that each got.

#149 fix: 如果OutputPaths / ErrorOutputPaths配置是本地文件，文件所在的路径不存在会抛出异常
  common/log/config.go
Labels: bug

#144 [ISSUE #138] support save RateLimit config into boltdb
  apiserver/httpserver/handler.go
  common/model/naming.go
  common/utils/funcs.go
  go.mod
  store/boltdb/circuitbreaker.go
  store/boltdb/default.go
  store/boltdb/handler.go
  store/boltdb/platform.go
  store/boltdb/ratelimit.go
  store/boltdb/ratelimit_test.go
Labels: bug, store

#155 [ISSUE #136] support auto create service when register instance
  go.mod
  naming/instance.go
  naming/server.go
  naming/test/instance_test.go
  store/boltdb/service.go
  test/instance_test.go
Labels: enhancement
