Repository polarismesh/polaris, pull requests merged in 2022-07, with the labels that each got.

#377 fix:修复db与server时区不一致导致的问题
  polaris-server.yaml
  store/sqldb/base_db.go
  store/sqldb/default.go
Labels: bug, service, need-feedback

#504 feat: refactor common/log
  common/log/config.go
  common/log/logger.go
  common/log/scope.go
Labels: code quality

#502 Dev/feature log archiving
  plugin/history/logger/history_logger.go
Labels: bug

#519 [ISSUE #516] support docker-image for standalone & support set port info when install standalone in VM
  .github/workflows/docker-standalone.yml
  .github/workflows/standalone.yml
  README-zh.md
  README.md
  deploy/standalone/docker/Dockerfile
  deploy/standalone/docker/build.sh
  deploy/standalone/docker/docker-compose.yaml
  deploy/standalone/docker/polaris-console.yaml
  deploy/standalone/vm/Dockerfile
  deploy/standalone/vm/install-darwin.sh
  deploy/standalone/vm/install-linux.sh
  deploy/standalone/vm/install-windows.ps1
  deploy/standalone/vm/port.properties
Labels: install

#527 [ISSUE #520] Fix issue 520
  .github/workflows/codecov.yaml
  .github/workflows/integration-testing-mysql.yml
  .github/workflows/integration-testing.yml
  plugin/healthchecker/heartbeatmemory/checker_memory.go
  plugin/healthchecker/heartbeatmemory/checker_memory_test.go
Labels: bug

#532 Feature/HideService
  apiserver/httpserver/server.go
  bootstrap/server.go
  cache/service_query.go
  cache/service_query_test.go
  cache/service_test.go
  polaris-server.yaml
  service/default.go
  service/server.go
  service/service.go
  service/test.yaml
Labels: enhancement, service, issue-shoot

#548 feat: support integration testing of healthCheckRedis
  .github/workflows/codecov.yaml
  .github/workflows/integration-testing-mysql.yml
  service/test_sqldb.yaml
Labels: test, code quality, issue-shoot
