Repository polarismesh/polaris, pull requests merged in 2022-10, with the labels that each got.

#718 Unit test auth
  .github/workflows/codecov.yaml
  apiserver/httpserver/i18n/README.MD
  apiserver/httpserver/i18n/cmd/gen.go
  apiserver/httpserver/i18n/en.toml
  apiserver/httpserver/i18n/messages.genearate.go
  apiserver/httpserver/i18n/zh.toml
  auth/defaultauth/common_test.go
  auth/defaultauth/main_test.go
Labels: test, code quality

#730 feat: update namespace for code style
  namespace/default.go
  namespace/namespace_authability.go
  namespace/server.go
  namespace/server_authability.go
  namespace/test_export.go
Labels: code quality

#743 fix:修复zh.toml中的错误码描述
  README-zh.md
  README.md
  apiserver/httpserver/i18n/zh.toml
  import-format.sh
Labels: bug

#754 feat: 修复正则表达式不生效问题
  apiserver/xdsserverv3/server.go
Labels: bug, xds

#755 [ISSUE #754] feat: 修复XDS正则表达式不生效问题
  apiserver/xdsserverv3/server.go
  store/sqldb/user.go
Labels: bug, xds

#761 fix: 移除platform和bussiness逻辑代码(#720)
  apiserver/eurekaserver/eureka_suit_test.go
  auth/defaultauth/main_test.go
  common/api/v1/response.go
  common/model/naming.go
  common/utils/common.go
  config/bootstrap_test.go
  plugin.go
  plugin/auth/platform/platform.go
  service/api.go
  service/api_v1.go
  service/main_test.go
  service/platform.go
  service/platform_authability.go
  store/boltdb/business.go
  store/boltdb/business_test.go
  store/boltdb/default.go
  store/boltdb/platform.go
  store/boltdb/platform_test.go
  store/boltdb/ratelimit_test.go
  store/discover_api.go
  store/mock/api_mock.go
  store/sqldb/business.go
  store/sqldb/default.go
  store/sqldb/platform.go
  store/sqldb/scripts/polaris_server.sql
Labels: code quality

#763 Golangci action part 1
  .github/workflows/go-test.yaml
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: code quality, github-action

#767 feat: organize part of the repetitive content
  .github/workflows/golangci-lint.yml
  .golangci.yml
  apiserver/grpcserver/base.go
  apiserver/grpcserver/discover/v1/client_access.go
  apiserver/grpcserver/discover/v2/client_access_v2.go
  apiserver/httpserver/http/handler.go
  apiserver/httpserver/server.go
  apiserver/httpserver/v1/naming_client_access.go
  apiserver/httpserver/v2/naming_client_access.go
  apiserver/prometheussd/server.go
  auth/defaultauth/utils.go
  common/log/config.go
  common/utils/collection.go
  common/utils/common.go
  common/utils/config_file.go
  common/utils/const.go
  config/api.go
  config/config_file.go
  config/config_file_group.go
  config/config_file_release.go
  config/config_file_release_history.go
  config/config_file_tag.go
  config/config_file_template.go
  config/utils/utils.go
  config/utils/utils_test.go
  namespace/namespace.go
  service/circuitbreaker_config.go
  service/client_info.go
  service/client_v1.go
  service/instance.go
  service/main_test.go
  service/ratelimit_config.go
  service/routing_config_v1.go
  service/routing_config_v2.go
  service/service.go
  service/service_alias.go
  service/utils.go
Labels: code quality

#770 feat: 丰富运维管理接口相关接口swagger信息
  apiserver/httpserver/maintain_access.go
  apiserver/httpserver/maintain_apidoc.go
  apiserver/httpserver/maintain_apinotes.go
  apiserver/httpserver/swagger_access.go
  go.mod
  go.sum
Labels: documentation

#768 feat: fix server exit or restart signal
  bootstrap/run_darwin.go
  bootstrap/run_linux.go
  bootstrap/run_windows.go
  bootstrap/server.go
Labels: enhancement, code quality

#773 feat: code style for cache package
  cache/cache.go
  cache/config_file.go
  cache/config_file_bucket.go
  cache/config_file_test.go
  cache/instance.go
  cache/l5.go
  cache/namespace.go
  cache/ratelimit_config.go
  cache/routing_config.go
  cache/routing_config_bucket.go
  cache/routing_config_query.go
  cache/service.go
  cache/service_query.go
  cache/strategy.go
  cache/user.go
  config/server_authability.go
Labels: code quality

#772 [ISSUE #760] 限流规则禁用SDK无法感知
  .github/workflows/golangci-lint.yml
  auth/defaultauth/group_test.go
  auth/defaultauth/strategy_test.go
  auth/defaultauth/user_test.go
  cache/routing_config_query.go
  cache/routing_config_query_test.go
  cache/test_export.go
  common/utils/funcs.go
  service/client_v1.go
  service/ratelimit_config.go
  service/ratelimit_config_test.go
  service/routing_config_v2.go
  store/boltdb/ratelimit.go
  store/boltdb/ratelimit_test.go
  store/sqldb/user.go
Labels: bug, test, code quality
