Repository polarismesh/polaris, pull requests merged in 2022-01, with the labels that each got.

#212 feat:fix typos
  apiserver/l5pbserver/naming.go
  naming/l5_service.go
  naming/namespace.go
  naming/test/namespace_test.go
  plugin/cmdb/memory/memory.go
  plugin/ratelimit/lrurate/lrurate_test.go
  store/boltdb/circuitbreaker.go
  store/boltdb/handler.go
  store/boltdb/instance.go
  store/boltdb/ratelimit.go
  store/boltdb/service.go
  test/circuitbreaker_config_test.go
  test/instance_test.go
  test/namespace_test.go
  test/ratelimit_config_test.go
  test/service_test.go
Labels: code quality

#220 fix: console_access.go interface response structure, use handler.WriteHeaderAndProto replace handler.WriteHeader
  apiserver/httpserver/console_access.go
Labels: apisever, code quality

#230 调整healthcheck目录
  apiserver/grpcserver/server.go
  apiserver/httpserver/server.go
  bootstrap/config/config.go
  bootstrap/server.go
  service/healthcheck/cache.go
  service/healthcheck/check.go
  service/healthcheck/config.go
  service/healthcheck/dispatch.go
  service/healthcheck/ketama.go
  service/healthcheck/report.go
  service/healthcheck/server.go
  service/healthcheck/time_adjust.go
Labels: keystone

#236 fix: retry write redis when redis connect fail
  common/redispool/redis_pool.go
Labels: enhancement, service

#238 feat: 支持eureka api接入
  apiserver/eurekaserver/access.go
  apiserver/eurekaserver/default.go
  apiserver/eurekaserver/model.go
  apiserver/eurekaserver/model_test.go
  apiserver/eurekaserver/server.go
  apiserver/eurekaserver/worker.go
  apiserver/eurekaserver/write.go
  apiserver/eurekaserver/xml.go
  apiserver/l5pbserver/server.go
  service/l5_service.go
  service/server.go
Labels: enhancement, apisever, service

#239 Add helm
  deploy/helm/.helmignore
  deploy/helm/Chart.yaml
  deploy/helm/README-zh.md
  deploy/helm/README.md
  deploy/helm/images/polaris.png
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/polaris-console-config.yaml
  deploy/helm/templates/polaris-server-config.yaml
  deploy/helm/templates/polaris-server.yaml
  deploy/helm/templates/prometheus.yaml
  deploy/helm/values.yaml
Labels: kubernetes, install

#241 [ISSUE #240] Add namespaces for statistics on services and instances
  cache/cache.go
  cache/instance.go
  cache/listener.go
  cache/service.go
  cache/service_test.go
  common/api/v1/service.pb.go
  common/api/v1/service.proto
  service/healthcheck/cache.go
  service/namespace.go
  test/namespace_test.go
Labels: enhancement, service

#258 improved comment and func args
  service/service.go
  service/service_alias.go
  service/utils.go
Labels: code quality
