Repository polarismesh/polaris, pull requests merged in 2022-12, with the labels that each got.

#835 fix: eureka同步时，实例不存在没有返回404，导致eureka触发不了重注册
  apiserver/eurekaserver/replicate.go
Labels: bug, service

#833 fix: eureka同步时，实例不存在没有返回404，导致eureka触发不了重注册
  apiserver/eurekaserver/replicate.go
Labels: bug

#843 Release v1.13.0
  deploy/standalone/vm/uninstall-windows.bat
  polaris-server.yaml
Labels: bug, install
