Repository polarismesh/polaris, pull requests merged in 2022-11, with the labels that each got.

#778 enrich naming swagger docs
  apiserver/httpserver/swagger_access.go
  apiserver/httpserver/v1/naming_client_access.go
  apiserver/httpserver/v1/naming_client_access_apidoc.go
  apiserver/httpserver/v1/naming_client_access_apinotes.go
  apiserver/httpserver/v1/naming_console_access.go
  apiserver/httpserver/v1/naming_console_access_apidoc.go
  apiserver/httpserver/v1/naming_console_access_apinotes.go
  apiserver/httpserver/v2/naming_client_access.go
  apiserver/httpserver/v2/naming_console_access.go
  apiserver/httpserver/v2/naming_console_access_apidoc.go
  apiserver/httpserver/v2/naming_console_access_apinotes.go
Labels: documentation

#780 修复：windows中修改端口后无效的问题
  deploy/standalone/vm/install-windows.ps1
Labels: install

#785 等待 apiserver 都启动完成，再自注册。
  apiserver/eurekaserver/eureka_suit_test.go
  apiserver/eurekaserver/server.go
  apiserver/grpcserver/config/server.go
  apiserver/grpcserver/discover/server.go
  apiserver/httpserver/server.go
  apiserver/l5pbserver/server.go
  apiserver/prometheussd/server.go
  apiserver/xdsserverv3/server.go
  bootstrap/server.go
  main.go
  plugin/whitelist/ip_whitelist_test.go
  store/sqldb/default.go
Labels: apiserver

#797 优化mysql参数判断
  store/sqldb/default.go
Labels: code quality

#796 feat: 北极星内部事件中心机制优化(#342)
  bootstrap/server.go
  common/eventhub/const.go
  common/eventhub/eventhub.go
  common/eventhub/eventhub_test.go
  common/eventhub/subscription.go
  common/eventhub/subscription_test.go
  common/eventhub/topic.go
  common/eventhub/topic_test.go
  plugin/discoverevent/local/event_local.go
  service/healthcheck/server.go
  service/healthcheck/test_export.go
  service/main_test.go
  service/server.go
Labels: enhancement

#809 支持 eureka 服务大小写不敏感在北极星的存储方式,调整集成测试。
  test/uplower_test.go
Labels: test

#810 feat: fix restart
  bootstrap/run_darwin.go
  bootstrap/run_linux.go
  go.sum
Labels: bug

#813 polaris 集群模式副本数取值错误问题
  deploy/helm/templates/polaris-server.yaml
Labels: install

#818 feat: support data sync between eureka and polaris
  apiserver/eurekaserver/access.go
  apiserver/eurekaserver/applications.go
  apiserver/eurekaserver/config.go
  apiserver/eurekaserver/delta_worker.go
  apiserver/eurekaserver/model.go
  apiserver/eurekaserver/replicate.go
  apiserver/eurekaserver/replicate_worker.go
  apiserver/eurekaserver/server.go
  apiserver/eurekaserver/write.go
  common/model/naming.go
  plugin/discoverevent/local/event_local.go
  plugin/discoverevent/local/event_local_test.go
  polaris-server.yaml
  service/healthcheck/check.go
  service/healthcheck/report.go
  service/instance.go
Labels: service, keystone, apiserver

#823 fix: 解决eureka同步时，出现存量服务同步失败的问题
  apiserver/eurekaserver/access.go
  apiserver/eurekaserver/replicate_worker.go
  bootstrap/server.go
  common/model/auth.go
Labels: bug, service
