Repository polarismesh/polaris, pull requests merged in 2022-06, with the labels that each got.

#401 feat: config/utils code adjust
  config/utils/utils.go
  config/utils/utils_test.go
Labels: code quality

#403 feat: add tls and acl options to redis configuration
  common/redispool/redis_pool.go
  deploy/helm/Chart.yaml
  deploy/helm/templates/polaris-server-config.yaml
  deploy/helm/values.yaml
  deploy/standalone/k8s/02-polaris-server-config.yaml
  go.mod
  go.sum
  polaris-server.yaml
  test/discover/test.yaml
Labels: enhancement, healthcheck, plugin

#408 feat: refactor redispool
  common/redispool/config_option.go
  common/redispool/config_option_test.go
  common/redispool/redis_pool.go
  go.sum
Labels: need discuss

#419 fully support all the eureka api
  apiserver/apiserver.go
  apiserver/eurekaserver/access.go
  apiserver/eurekaserver/applications.go
  apiserver/eurekaserver/applications_test.go
  apiserver/eurekaserver/config.go
  apiserver/eurekaserver/model.go
  apiserver/eurekaserver/server.go
  apiserver/eurekaserver/tool.go
  apiserver/eurekaserver/vip.go
  apiserver/eurekaserver/vip_test.go
  apiserver/eurekaserver/worker.go
  apiserver/eurekaserver/write.go
  go.mod
  go.sum
Labels: enhancement, apisever, service

#433 [fix] 自己掉自己的问题
  config/config_file_authibility.go
Labels: bug, config

#442 修改CHARSET = utf8mb4 COLLATE = utf8mb4_bin;
  store/sqldb/scripts/delta/v160-v170.sql
  store/sqldb/scripts/delta/v170-v180.sql
  store/sqldb/scripts/polaris_server.sql
Labels: store, issue-shoot

#444 修改编译任务支持arm64版本打包
  .github/workflows/release.yml
  .github/workflows/standalone.yml
  .github/workflows/testing.yml
Labels: install, issue-shoot

#465 [ISSUE #452] Service cache not refresh when service delete
  .github/workflows/codecov.yaml
  .github/workflows/testing.yml
  auth/defaultauth/user.go
  auth/defaultauth/user_test.go
  cache/cache_test.go
  cache/strategy.go
  cache/strategy_test.go
  cache/user.go
  config/bootstrap_test.go
  config/client_test.go
  config/config_file_group_test.go
  config/config_file_test.go
  config/server.go
  config/test.yaml
  plugin/discoverstat/discoverlocal/local_test.go
  store/boltdb/business.go
  store/boltdb/circuitbreaker.go
  store/boltdb/circuitbreaker_test.go
  store/boltdb/client.go
  store/boltdb/config_file.go
  store/boltdb/config_file_group.go
  store/boltdb/config_file_release.go
  store/boltdb/group.go
  store/boltdb/handler_test.go
  store/boltdb/instance.go
  store/boltdb/platform.go
  store/boltdb/ratelimit.go
  store/boltdb/routing.go
  store/boltdb/service.go
  store/boltdb/strategy.go
  store/boltdb/user.go
  test/config_center/README.md
  test/config_center/bootstrap_test.go
  test/config_center/plugin_test.go
  test/discover/main_test.go
  test/discover/test.yaml
Labels: bug, test

#486 [ISSUE #485] fix not permission when crontab run check.sh
  apiserver/eurekaserver/server.go
  apiserver/httpserver/server.go
  tool/include
Labels: install
